### PR TITLE
Filters bad stop_times RTDII-194

### PR DESCRIPTION
**Pull request by weatherpattern**
**Summary:**

Checks if a stop_time in `stop_times.txt` is missing a `stop`, `startServiceArea`, and `endServiceArea`.
With gtfs-flex, `stop` is optional, however, if it is not used, there must be at least one service area.

**Expected behavior:** 

If a stop_time is missing a `stop`, `startServiceArea`, and `endServiceArea`, throw `NoSuchElementException`.
To test run: `GTFSReadertest.testStopTimesGtfs()`

- [X] Run the unit tests with `mvn test` to make sure you didn't break anything
- [X] Format the title like "Fix #<issue_number> - short description of fix and changes"
- [X] Linked all relevant issues

### CODE REVIEW

**Review by mmaranda-cs — COMMENTED** [review]
Why is the check being done in GtfsReader.java? It would be better for StopTime to have the validation method in it as well as being able to throw the appropriate method.  This class should just iterate over all the StopTime entries and have StopTime validate itself.  It helps encapsulate the validation into StopTime which is good OOD.

**Review by mmaranda-cs — COMMENTED** [review]
This error message looks like it will be hard to track down the offending StopTime Unless the StopTime ID is included in the message.  If it is then it should be used as part of the test to make sure the error is failing at the appropriate data entry on the test.

**Comment by weatherpattern** [comment]
Moved validation method to `StopTime` class
Narrowed unit test to test for the bad `stop_time` row in test data file `test_stop_times.zip`

**Comment by mmaranda-cs** [comment]
These changes look good.

**Pull request merged**
